// Script to populate vendors with complete data from spreadsheet
const vendorData = [
  {
    name: "Abbott Northwestern Hospital",
    type: "healthcare",
    registrationNumber: "1234567890",
    grhType: "Hospital",
    contactPerson: "John Smith",
    keyPerson: "Dr. Sarah Johnson",
    phone: "(612) 863-4000",
    email: "info@abbottnorthwestern.com",
    address: "800 E 28th St, Minneapolis, MN 55407",
    website: "https://www.abbottnorthwestern.com",
    services: ["Emergency Care", "Cardiology", "Neurology", "Orthopedics"],
    serviceArea: "Minneapolis Metro",
    capacity: 631,
    dailyRate: "450.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Major teaching hospital with comprehensive services"
  },
  {
    name: "Allina Health",
    type: "healthcare",
    registrationNumber: "1234567891",
    grhType: "Health System",
    contactPerson: "Lisa Anderson",
    keyPerson: "Dr. Michael Brown",
    phone: "(612) 775-2000",
    email: "contact@allina.com",
    address: "2925 Chicago Ave, Minneapolis, MN 55407",
    website: "https://www.allinahealth.org",
    services: ["Primary Care", "Specialty Care", "Emergency Services"],
    serviceArea: "Minnesota & Wisconsin",
    capacity: 2500,
    dailyRate: "420.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Integrated health system serving Minnesota and Wisconsin"
  },
  {
    name: "Children's Hospital & Clinics of Minnesota",
    type: "healthcare",
    registrationNumber: "1234567892",
    grhType: "Pediatric Hospital",
    contactPerson: "Mary Wilson",
    keyPerson: "Dr. Jennifer Davis",
    phone: "(612) 813-6100",
    email: "info@childrensmn.org",
    address: "2525 Chicago Ave S, Minneapolis, MN 55404",
    website: "https://www.childrensmn.org",
    services: ["Pediatric Care", "Neonatal ICU", "Pediatric Surgery"],
    serviceArea: "Upper Midwest",
    capacity: 400,
    dailyRate: "520.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Specialized pediatric care facility"
  },
  {
    name: "Mayo Clinic",
    type: "healthcare",
    registrationNumber: "1234567893",
    grhType: "Academic Medical Center",
    contactPerson: "Robert Johnson",
    keyPerson: "Dr. Elizabeth Smith",
    phone: "(507) 284-2511",
    email: "info@mayo.edu",
    address: "200 1st St SW, Rochester, MN 55905",
    website: "https://www.mayoclinic.org",
    services: ["Specialized Medicine", "Research", "Education"],
    serviceArea: "International",
    capacity: 1265,
    dailyRate: "680.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "World-renowned medical center"
  },
  {
    name: "Regions Hospital",
    type: "healthcare",
    registrationNumber: "1234567894",
    grhType: "Regional Hospital",
    contactPerson: "Susan Miller",
    keyPerson: "Dr. David Wilson",
    phone: "(651) 254-3456",
    email: "info@regionshospital.com",
    address: "640 Jackson St, St Paul, MN 55101",
    website: "https://www.regionshospital.com",
    services: ["Emergency Care", "Trauma Center", "Burn Center"],
    serviceArea: "Twin Cities Metro",
    capacity: 454,
    dailyRate: "465.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Level I trauma center"
  },
  {
    name: "Sunrise of Edina",
    type: "group_home",
    registrationNumber: "GH001234",
    grhType: "Assisted Living",
    contactPerson: "Patricia Garcia",
    keyPerson: "Administrator: Jane Thompson",
    phone: "(952) 830-9392",
    email: "edina@sunriseseniorliving.com",
    address: "4265 W 65th St, Edina, MN 55435",
    website: "https://www.sunriseseniorliving.com",
    services: ["Assisted Living", "Memory Care", "Skilled Nursing"],
    serviceArea: "Edina",
    capacity: 125,
    dailyRate: "185.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-06-30",
    status: "active",
    notes: "Premium assisted living community"
  },
  {
    name: "Walker Methodist",
    type: "group_home",
    registrationNumber: "GH001235",
    grhType: "Senior Living",
    contactPerson: "Mark Anderson",
    keyPerson: "Director: Carol Johnson",
    phone: "(952) 873-2200",
    email: "info@walkermethodist.org",
    address: "3737 Bryant Ave S, Minneapolis, MN 55409",
    website: "https://www.walkermethodist.org",
    services: ["Independent Living", "Assisted Living", "Memory Care"],
    serviceArea: "Minneapolis Metro",
    capacity: 200,
    dailyRate: "165.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-08-31",
    status: "active",
    notes: "Non-profit senior living community"
  },
  {
    name: "Hennepin County Housing",
    type: "county_hopwa",
    registrationNumber: "HC2024001",
    grhType: "County Agency",
    contactPerson: "Jennifer Martinez",
    keyPerson: "Program Manager: Tom Wilson",
    phone: "(612) 348-2000",
    email: "housing@hennepin.us",
    address: "300 S 6th St, Minneapolis, MN 55487",
    website: "https://www.hennepin.us/housing",
    services: ["Housing Assistance", "HOPWA Program", "Emergency Housing"],
    serviceArea: "Hennepin County",
    capacity: 1500,
    dailyRate: "85.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "County housing authority"
  },
  {
    name: "Ramsey County Social Services",
    type: "county_hopwa",
    registrationNumber: "RC2024001",
    grhType: "County Agency",
    contactPerson: "Michelle Thompson",
    keyPerson: "Director: Kevin Davis",
    phone: "(651) 266-4444",
    email: "socialservices@ramsey.us",
    address: "160 E Kellogg Blvd, St Paul, MN 55101",
    website: "https://www.ramsey.us/social-services",
    services: ["Social Services", "Housing Programs", "Emergency Assistance"],
    serviceArea: "Ramsey County",
    capacity: 1200,
    dailyRate: "80.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "County social services department"
  },
  {
    name: "Minneapolis Public Housing Authority",
    type: "other_subsidies",
    registrationNumber: "MPHA2024",
    grhType: "Housing Authority",
    contactPerson: "Angela Rodriguez",
    keyPerson: "Executive Director: Sarah Johnson",
    phone: "(612) 342-1400",
    email: "info@mphaonline.org",
    address: "1001 Washington Ave N, Minneapolis, MN 55401",
    website: "https://www.mphaonline.org",
    services: ["Public Housing", "Section 8", "Affordable Housing"],
    serviceArea: "Minneapolis",
    capacity: 6000,
    dailyRate: "65.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Public housing authority"
  },
  {
    name: "CommonBond Communities",
    type: "other_subsidies",
    registrationNumber: "CB2024001",
    grhType: "Non-profit Housing",
    contactPerson: "Rebecca Brown",
    keyPerson: "CEO: Michael Johnson",
    phone: "(651) 292-8710",
    email: "info@commonbond.org",
    address: "401 N 2nd St, Minneapolis, MN 55401",
    website: "https://www.commonbond.org",
    services: ["Affordable Housing", "Community Development", "Social Services"],
    serviceArea: "Minnesota",
    capacity: 3500,
    dailyRate: "70.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Non-profit affordable housing developer"
  },
  {
    name: "Aeon",
    type: "other_subsidies",
    registrationNumber: "AEON2024",
    grhType: "Non-profit Housing",
    contactPerson: "David Kim",
    keyPerson: "President: Lisa Smith",
    phone: "(612) 341-3148",
    email: "info@aeonmn.org",
    address: "1600 University Ave W, St Paul, MN 55104",
    website: "https://www.aeonmn.org",
    services: ["Affordable Housing", "Property Management", "Community Programs"],
    serviceArea: "Twin Cities",
    capacity: 2800,
    dailyRate: "68.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Non-profit housing organization"
  },
  {
    name: "Habitat for Humanity Twin Cities",
    type: "other_subsidies",
    registrationNumber: "HFH2024",
    grhType: "Non-profit Housing",
    contactPerson: "Emily Johnson",
    keyPerson: "CEO: Susan Miller",
    phone: "(651) 405-1300",
    email: "info@tchabitat.org",
    address: "1954 University Ave W, St Paul, MN 55104",
    website: "https://www.tchabitat.org",
    services: ["Homeownership", "Housing Repair", "Community Development"],
    serviceArea: "Twin Cities",
    capacity: 150,
    dailyRate: "45.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Non-profit homebuilding organization"
  },
  {
    name: "Lutheran Social Service",
    type: "other_subsidies",
    registrationNumber: "LSS2024",
    grhType: "Faith-based Non-profit",
    contactPerson: "Pastor John Anderson",
    keyPerson: "Executive Director: Mary Wilson",
    phone: "(651) 224-3344",
    email: "info@lssmn.org",
    address: "2485 Como Ave, St Paul, MN 55108",
    website: "https://www.lssmn.org",
    services: ["Housing Services", "Mental Health", "Family Services"],
    serviceArea: "Minnesota",
    capacity: 800,
    dailyRate: "75.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Faith-based social services organization"
  },
  {
    name: "Catholic Charities of St. Paul and Minneapolis",
    type: "other_subsidies",
    registrationNumber: "CC2024",
    grhType: "Faith-based Non-profit",
    contactPerson: "Father Michael Davis",
    keyPerson: "Executive Director: Patricia Garcia",
    phone: "(651) 222-0311",
    email: "info@cctwincities.org",
    address: "1276 University Ave W, St Paul, MN 55104",
    website: "https://www.cctwincities.org",
    services: ["Housing Services", "Immigration Services", "Food Assistance"],
    serviceArea: "Twin Cities",
    capacity: 600,
    dailyRate: "72.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Faith-based social services organization"
  },
  {
    name: "Salvation Army",
    type: "other_subsidies",
    registrationNumber: "SA2024",
    grhType: "Faith-based Non-profit",
    contactPerson: "Major Robert Johnson",
    keyPerson: "Area Commander: Major Susan Brown",
    phone: "(651) 645-6406",
    email: "info@salvationarmynorth.org",
    address: "900 N 4th St, Minneapolis, MN 55401",
    website: "https://www.salvationarmynorth.org",
    services: ["Emergency Housing", "Transitional Housing", "Social Services"],
    serviceArea: "Twin Cities",
    capacity: 400,
    dailyRate: "65.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Faith-based emergency services organization"
  },
  {
    name: "People Serving People",
    type: "other_subsidies",
    registrationNumber: "PSP2024",
    grhType: "Homeless Services",
    contactPerson: "Jennifer Martinez",
    keyPerson: "Executive Director: Tom Wilson",
    phone: "(612) 338-4307",
    email: "info@peopleservingpeople.org",
    address: "614 3rd Ave S, Minneapolis, MN 55402",
    website: "https://www.peopleservingpeople.org",
    services: ["Emergency Shelter", "Transitional Housing", "Family Services"],
    serviceArea: "Minneapolis",
    capacity: 300,
    dailyRate: "55.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Homeless services organization"
  },
  {
    name: "Simpson Housing Services",
    type: "other_subsidies",
    registrationNumber: "SHS2024",
    grhType: "Homeless Services",
    contactPerson: "Michelle Thompson",
    keyPerson: "CEO: Kevin Davis",
    phone: "(612) 341-2700",
    email: "info@simpsonhousing.org",
    address: "2100 Pillsbury Ave S, Minneapolis, MN 55404",
    website: "https://www.simpsonhousing.org",
    services: ["Permanent Supportive Housing", "Transitional Housing", "Mental Health"],
    serviceArea: "Minneapolis",
    capacity: 250,
    dailyRate: "60.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Supportive housing organization"
  },
  {
    name: "Beacon Interfaith Housing Collaborative",
    type: "other_subsidies",
    registrationNumber: "BIHC2024",
    grhType: "Faith-based Housing",
    contactPerson: "Angela Rodriguez",
    keyPerson: "Executive Director: Sarah Johnson",
    phone: "(651) 789-7000",
    email: "info@beaconinterfaith.org",
    address: "2801 21st Ave S, Minneapolis, MN 55407",
    website: "https://www.beaconinterfaith.org",
    services: ["Affordable Housing", "Supportive Services", "Community Development"],
    serviceArea: "Twin Cities",
    capacity: 180,
    dailyRate: "58.00",
    contractStartDate: "2024-01-01",
    contractEndDate: "2024-12-31",
    licenseStatus: "active",
    licenseExpirationDate: "2025-12-31",
    status: "active",
    notes: "Faith-based housing collaborative"
  }
];

// Function to insert vendor data
async function populateVendors() {
  const baseUrl = 'http://localhost:5000';
  
  for (const vendor of vendorData) {
    try {
      const response = await fetch(`${baseUrl}/api/vendors`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(vendor)
      });
      
      if (response.ok) {
        console.log(`✓ Added vendor: ${vendor.name}`);
      } else {
        console.log(`✗ Failed to add vendor: ${vendor.name}`, await response.text());
      }
    } catch (error) {
      console.log(`✗ Error adding vendor: ${vendor.name}`, error.message);
    }
  }
}

// Run the population script
populateVendors().then(() => {
  console.log('Vendor population complete!');
}).catch(error => {
  console.error('Population script failed:', error);
});